version: "3.9"
services:
  postgres:
    container_name: postgres_test
    build: .
    environment:
      POSTGRES_DB: "scheduletest"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5433:5432"
volumes:
  scheduletest: