version: "3.9"
services:
  postgres:
    container_name: postgres
    build: .
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      # Applies initial scripts on startup
      - ./init:/docker-entrypoint-initdb.d
      # Persist the data between container invocations
      - test-volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  test-volume: